### ISSUE TITLE
Issues with Hero Creation Tool for 5E Module

### ISSUE THREAD

**Issue by Ehill05** [btbias/5e-complete#1]
Not certain if this is an appropriate issue submission (this is my first real issue submission), but I've been testing out the module and am very happy that this is happening! It does however seem to break the Hero Creation Tool module in certain ways? Having spells selected as a source breaks everything in the Hero Creation Tool. Having Races or Racial Features does not seem to link properly. Subclasses do not link properly. Backgrounds do not link properly. Not certain if this is a general issue of formatting, or an issue totally on the Hero Creation Tool side.

**Comment by btbias** [comment]
Honestly, I have no idea on this one. I've never used Hero Creation Tool, just the built-in automatic leveling included with the dnd5e system. Maybe I could ask around and get some info on that for you.

**Comment by Ehill05** [comment]
Completely understand!  I just thought I'd list it as a thing.  My guess is that it's some sort of a formatting issue somewhere along the line?  At least if someone finds this module and tries to use the Hero tool they may find this and see it's not just them.

**Comment by btbias** [comment]
I went ahead and installed it to see what I could do, and it doesn't seem to work at all... is it v10 compatible/are you using v10? Cause even with the SRD compendia selected, nothing shows up in the tool... D:

**Comment by Ehill05** [comment]
Did you select the sources?  That was my first mistake when I loaded it up, I hadn’t gone into the configuration and selected sources.  -Eric Sent from Mail for Windows From: btbiasSent: Wednesday, November 23, 2022 2:10 AMTo: btbias/5e-completeCc: Ehill05; AuthorSubject: Re: [btbias/5e-complete] Issues with Hero Creation Tool for 5E Module (Issue #1) I went ahead and installed it to see what I could do, and it doesn't seem to work at all... is it v10 compatible/are you using v10? Cause even with the SRD compendia selected, nothing shows up in the tool... D:—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by btbias** [comment]
I did, yeah! In fact they were already configured right away. I think it's a v10 issue cause the GitHub says it's v9 compatible.

**Comment by Ehill05** [comment]
Hmm, good to know!  I’ll keep an eye on it getting updated and test it out then! Sent from Mail for Windows From: btbiasSent: Friday, November 25, 2022 6:42 PMTo: btbias/5e-completeCc: Ehill05; AuthorSubject: Re: [btbias/5e-complete] Issues with Hero Creation Tool for 5E Module (Issue #1) I did, yeah! In fact they were already configured right away. I think it's a v10 issue cause the GitHub says it's v9 compatible.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by btbias** [comment]
Alrighty, let me know if anything changes down the road!
