### ISSUE TITLE
Images <issing

### ISSUE THREAD

**Issue by marcusvinnicius** [btbias/5e-complete#5]
Soe images are missing from the creature companion (like Aartuk warrior)

**Comment by btbias** [comment]
This is a known problem, which is currently listed in the readme. Frankly, I don't know the best way to provide artwork for every creature without running into copyright issues; most of the tokens I like to use are ones I've purchased from artists, and I don't want to redistribute them.

Any suggestions to work around that are welcome.

**Comment by btbias** [comment]
Haven't heard from you so I'll close this in the meantime. If you think of something I can do to obtain copyright-free images for all 5e monsters please create a suggestion or shoot me a message on Discord, user `btbias#9324`.
