### ISSUE TITLE
Module not upgrading from 0.3.3 to 0.3.4

### ISSUE THREAD

**Issue by Ehill05** [btbias/5e-complete#6]
Foundry updates the module every time, but it does not move beyond 0.3.3.

**Comment by btbias** [comment]
Please try installing again using the manifest URL instead of Foundry's automatic update. I had a small issue with how I created 0.3.4 which has been fixed in 0.3.5.

**Comment by btbias** [comment]
Since I haven't heard back on this I'm hoping the issue's been resolved in the latest patch. If not, please let me know!
