### ISSUE TITLE
Missing Parameters

### ISSUE THREAD

**Issue by Ancyker** [btbias/5e-complete#7]
Some things, notably subraces, and spells, are missing some information that makes a lot of modules break.

For instance, a lot of subraces are missing the system field. The system field is used by addons for specific systems to make sure they aren't showing things from the wrong system. Everything should probably have this field.

Another example, some spells are missing the level field. This breaks the [character creation tool](https://github.com/HeroCreationLab/hero-creation-tool) that I use when it tries to check the level of the spell.

**Comment by btbias** [comment]
Aha, I was wondering about that! But to my knowledge that's not a field within the Foundry GUI, right? So I'll have to go in and add it directly to the database objects.

As for spells missing the level field, do you happen to know which ones so I can update them?

**Comment by Ancyker** [comment]
> Aha, I was wondering about that! But to my knowledge that's not a field within the Foundry GUI, right? So I'll have to go in and add it directly to the database objects.

It's not; it's set when the items are created, and it's normally present when they are exported.

> As for spells missing the level field, do you happen to know which ones so I can update them?

It didn't say, but when I looked most did seem to have it, so I think only a couple are missing level.

**Comment by btbias** [comment]
Is there a way to reach out to you on Discord or similar platform? I'm definitely more familiar with the front-end and would love to ask a question or two as they come up so I can make this compatible with Hero Creation Tool..

**Comment by Ancyker** [comment]
Discord is Ancyker#0001

**Comment by btbias** [comment]
Great, shot you a friend request. Thanks!

**Comment by btbias** [comment]
Fixed in Release 0.6.0
